In [1]:
# Initialize Otter
import otter
grader = otter.Notebook("hwk2-task3-aqi.ipynb")

# Task 3: Visualizing AQI during the 2017 Thomas Fire in Santa Barbara County

This task covers topics on the lesson on [time series](https://meds-eds-220.github.io/MEDS-eds-220-course/book/chapters/lesson-7-time-series.html). 

## Instructions 

- First, update the following cell to have a link to *your* Homework 2 GitHub repository:

**UPDATE THIS LINK**
https://github.com/MEDS-eds-220/eds220-hwk2


- Review the [complete rubric for this task](https://docs.google.com/document/d/1x0BoU6IH4cnOR1-n7i9CYQ9wUC37yDpYlQ4j6rCfcsU/edit?tab=t.0) before starting.

- **Make at least 5 commits. Generally, commit every time you finish a major step.** We'll check your repository and view the commit history.

- **Add comments for all your code.** Err on the side of commenting too much for now. Comments should follow best practices.

- **Do not update the top cell with the `otter` import**, this is used internally for grading.


## About the data

In this task you will use [Air Quality Index (AQI)](https://www.airnow.gov/aqi/aqi-basics/) data from the [US Environmental Protection Agency](https://www.epa.gov) to visualize the impact on the AQI of the 2017 [Thomas Fire](https://en.wikipedia.org/wiki/Thomas_Fire) in Santa Barbara County.

## FINAL CODE

You will use the next code cell to complete the last exercise in the task. Leave it blank for now.

## 1

a. Read the [Air Quality Index (AQI) Basics](https://www.airnow.gov/aqi/aqi-basics/) from the AirNow.gov portal.

b. Go to [EPA's website on Air Quality Data Collected at Outdoor Monitors Across the US](https://www.epa.gov/outdoor-air-quality-data).

c. Under "Download Data", click on "Pre-generated Data Files".

d. Read the "About the data" section.

## 2
a. Back in the "Pre-generated Data Files" site, click on "Tables of Daily AQI".

b. Download the 2017 Daily AQI **by County** ZIP file `daily_aqi_by_county_2017.zip` and the 2018 Daily AQI **by County** ZIP file `daily_aqi_by_county_2018.zip`. Save both files in the same folder as this notebook.

We will be reading the data directly from the local ZIP files. Each ZIP file contains a single CSV that has been compressed to save space.

<!-- BEGIN QUESTION -->

c. In the next code cell read in the data from the local ZIP file using the [`pd.read_csv`] function with the `compression='zip'` parameter added and store it as `aqi_17`.

d. In the same cell, read in the data for the 2018 Daily AQI by County ZIP file and store it as `aqi_18`.

In [2]:
# Import pandas
import pandas as pd

# Read in data as a zip file
aqi_17 = pd.read_csv("daily_aqi_by_county_2017.zip", compression="zip")
aqi_18 = pd.read_csv("daily_aqi_by_county_2018.zip", compression="zip")

<!-- END QUESTION -->

## 3
a. and b. Use the next two code cells to look at the head of both data frames. Store your results in `aqi_17_head` and `aqi_18_head`.

In [3]:
# a. Use .head() to see the first 5 rows of aqi_17
aqi_17_head = aqi_17.head()

In [4]:
# b. Use .head() to see the first 5 rows of aqi_18
aqi_18_head = aqi_18.head()

In [5]:
grader.check("q3_a")

q3_a results: All test cases passed!

<!-- BEGIN QUESTION -->

c. Use this code cell to make some other preliminary data exploration of your choosing.

In [6]:
# Use .tail() to look at the last 5 rows 
print(aqi_17.tail())

# View key information of data frame
print(aqi_17.info())

# Check the amount of NaN in each column
print(aqi_17.isna().sum())

       State Name county Name  State Code  County Code        Date  AQI  \
326796    Wyoming      Weston          56           45  2017-12-27   39
326797    Wyoming      Weston          56           45  2017-12-28   36
326798    Wyoming      Weston          56           45  2017-12-29   31
326799    Wyoming      Weston          56           45  2017-12-30   31
326800    Wyoming      Weston          56           45  2017-12-31   26

       Category Defining Parameter Defining Site  Number of Sites Reporting
326796     Good              Ozone   56-045-0003                          1
326797     Good              Ozone   56-045-0003                          1
326798     Good              Ozone   56-045-0003                          1
326799     Good              Ozone   56-045-0003                          1
326800     Good              Ozone   56-045-0003                          1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 326801 entries, 0 to 326800
Data columns (total 10 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   State Name                 326801 non-null  object
 1   county Name                326801 non-null  object
 2   State Code                 326801 non-null  int64
 3   County Code                326801 non-null  int64
 4   Date                       326801 non-null  object
 5   AQI                        326801 non-null  int64
 6   Category                   326801 non-null  object
 7   Defining Parameter         326801 non-null  object
 8   Defining Site              326801 non-null  object
 9   Number of Sites Reporting  326801 non-null  int64
dtypes: int64(4), object(6)
memory usage: 24.9+ MB
None
State Name                   0
county Name                  0
State Code                   0
County Code                  0
Date                         0
AQI                          0
Category                     0
Defining Parameter           0
Defining Site                0
Number of Sites Reporting    0
dtype: int64

In [7]:
# Use .tail() to look at the last 5 rows 
print(aqi_18.tail())

# View key information of data frame
print(aqi_18.info())

# Check the amount of NaN in each column
print(aqi_18.isna().sum())

       State Name county Name  State Code  County Code        Date  AQI  \
327536    Wyoming      Weston          56           45  2018-12-27   36
327537    Wyoming      Weston          56           45  2018-12-28   35
327538    Wyoming      Weston          56           45  2018-12-29   35
327539    Wyoming      Weston          56           45  2018-12-30   31
327540    Wyoming      Weston          56           45  2018-12-31   35

       Category Defining Parameter Defining Site  Number of Sites Reporting
327536     Good              Ozone   56-045-0003                          1
327537     Good              Ozone   56-045-0003                          1
327538     Good              Ozone   56-045-0003                          1
327539     Good              Ozone   56-045-0003                          1
327540     Good              Ozone   56-045-0003                          1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 327541 entries, 0 to 327540
Data columns (total 10 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   State Name                 327541 non-null  object
 1   county Name                327541 non-null  object
 2   State Code                 327541 non-null  int64
 3   County Code                327541 non-null  int64
 4   Date                       327541 non-null  object
 5   AQI                        327541 non-null  int64
 6   Category                   327541 non-null  object
 7   Defining Parameter         327541 non-null  object
 8   Defining Site              327541 non-null  object
 9   Number of Sites Reporting  327541 non-null  int64
dtypes: int64(4), object(6)
memory usage: 25.0+ MB
None
State Name                   0
county Name                  0
State Code                   0
County Code                  0
Date                         0
AQI                          0
Category                     0
Defining Parameter           0
Defining Site                0
Number of Sites Reporting    0
dtype: int64

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

d. Use this markdown cell to explain why you decided to do the exploration in c. and what information you obtained from doing it.

In my exploratory analysis of the data frame I used .tail() to look at the last 5 rows. To view key information of the data frame I used .info() to see the top 5 rows alonf with thier desiganted dtype. Finally, I found all of the NaNs in each column and it provided intersting insight that colum notesRegCode has most entires missing.

<!-- END QUESTION -->

## 4
We currently have two separate data frames. For this exercise we will need to "glue" them one on top of the other. The `pandas` function `pd.concat()` can achieve this. 

Pass `[aqi_17, aqi_18]` as the input of `pd.concat()` and store the output as `aqi`.  
In the next line run `aqi`.

NOTE: When we concatenate data frames like this, without any extra parameters for `pd.concat()` the indices for the two data frames are just "glued together", the index of the resulting data frame is not updated to start from 0. Notice the mismatch between the index of `aqi` and the number of rows in the complete data frame.

In [8]:
aqi = pd.concat([aqi_17, aqi_18])
aqi

,State Name,county Name,State Code,County Code,Date,AQI,Category,Defining Parameter,Defining Site,Number of Sites Reporting
0,Alabama,Baldwin,1,3,2017-01-01,28,Good,PM2.5,01-003-0010,1
1,Alabama,Baldwin,1,3,2017-01-04,29,Good,PM2.5,01-003-0010,1
2,Alabama,Baldwin,1,3,2017-01-10,25,Good,PM2.5,01-003-0010,1
3,Alabama,Baldwin,1,3,2017-01-13,40,Good,PM2.5,01-003-0010,1
4,Alabama,Baldwin,1,3,2017-01-16,22,Good,PM2.5,01-003-0010,1
...,...,...,...,...,...,...,...,...,...,...
327536,Wyoming,Weston,56,45,2018-12-27,36,Good,Ozone,56-045-0003,1
327537,Wyoming,Weston,56,45,2018-12-28,35,Good,Ozone,56-045-0003,1
327538,Wyoming,Weston,56,45,2018-12-29,35,Good,Ozone,56-045-0003,1
327539,Wyoming,Weston,56,45,2018-12-30,31,Good,Ozone,56-045-0003,1
327540,Wyoming,Weston,56,45,2018-12-31,35,Good,Ozone,56-045-0003,1

In [9]:
grader.check("q4")

q4 results: All test cases passed!

<!-- BEGIN QUESTION -->

## 5

Run the following code cell and use the next markdown cell to give a line by line explanation of the code below the comment "#Simplify column names". You might need to look up the `pandas` documentation.

In [10]:
# Initial column names: notice caps and spaces (difficult to work with!)
print(aqi.columns, '\n')

# Simplify column names
aqi.columns = (aqi.columns
                  .str.lower()
                  .str.replace(' ','_')
                )
print(aqi.columns, '\n')

Index(['State Name', 'county Name', 'State Code', 'County Code', 'Date', 'AQI',
       'Category', 'Defining Parameter', 'Defining Site',
       'Number of Sites Reporting'],
      dtype='object')

Index(['state_name', 'county_name', 'state_code', 'county_code', 'date', 'aqi',
       'category', 'defining_parameter', 'defining_site',
       'number_of_sites_reporting'],
      dtype='object')

aqi.columns: Select our data frames columns

.str.lower(): Turns all of the capital letters in the strong to lowercase 

.str.replace(' ','_'): Replace every space in the strings with an underscore _

Ensure to set it all back to aqi.columns to keep the changes in the data frame

<!-- END QUESTION -->

## 6
In the next code cell:

a. Select only data from `Santa Barbara` county and store it in a new variable `aqi_sb`.

b. Remove the `state_name`, `county_name`, `state_code` and `county_code` columns from `aqi_sb`.

Your data frame should have the following columns in this order: `date`, `aqi`, `category`, `defining_parameter`, `defining_site`, `number_of_sites_reporting`.

In [11]:
aqi['county_name'].unique()

array(['Baldwin', 'Clay', 'Colbert', 'DeKalb', 'Elmore', 'Etowah',
       'Houston', 'Jefferson', 'Lawrence', 'Madison', 'Mobile',
       'Montgomery', 'Morgan', 'Russell', 'Shelby', 'Sumter', 'Talladega',
       'Tuscaloosa', 'Aleutians East ', 'Anchorage ', 'Denali ',
       'Fairbanks North Star ', 'Juneau ', 'Kenai Peninsula ',
       'Matanuska-Susitna ', 'Apache', 'Cochise', 'Coconino', 'Gila',
       'La Paz', 'Maricopa', 'Mohave', 'Navajo', 'Pima', 'Pinal',
       'Santa Cruz', 'Yavapai', 'Yuma', 'Arkansas', 'Ashley', 'Clark',
       'Crittenden', 'Garland', 'Jackson', 'Newton', 'Polk', 'Pulaski',
       'Union', 'Washington', 'Alameda', 'Amador', 'Butte', 'Calaveras',
       'Colusa', 'Contra Costa', 'Del Norte', 'El Dorado', 'Fresno',
       'Glenn', 'Humboldt', 'Imperial', 'Inyo', 'Kern', 'Kings', 'Lake',
       'Los Angeles', 'Madera', 'Marin', 'Mariposa', 'Mendocino',
       'Merced', 'Mono', 'Monterey', 'Napa', 'Nevada', 'Orange', 'Placer',
       'Plumas', 'Riverside', 'Sacramento', 'San Benito',
       'San Bernardino', 'San Diego', 'San Francisco', 'San Joaquin',
       'San Luis Obispo', 'San Mateo', 'Santa Barbara', 'Santa Clara',
       'Shasta', 'Siskiyou', 'Solano', 'Sonoma', 'Stanislaus', 'Sutter',
       'Tehama', 'Trinity', 'Tulare', 'Tuolumne', 'Ventura', 'Yolo',
       'Adams', 'Alamosa', 'Arapahoe', 'Archuleta', 'Boulder', 'Chaffee',
       'Clear Creek', 'Delta', 'Denver', 'Douglas', 'El Paso', 'Fremont',
       'Garfield', 'Grand', 'Gunnison', 'La Plata', 'Larimer', 'Mesa',
       'Moffat', 'Montezuma', 'Montrose', 'Park', 'Pitkin', 'Prowers',
       'Pueblo', 'Rio Blanco', 'Routt', 'San Juan', 'San Miguel', 'Weld',
       'Fairfield', 'Hartford', 'Litchfield', 'Middlesex', 'New Haven',
       'New London', 'Tolland', 'Windham', 'BAJA CALIFORNIA NORTE',
       'SONORA', 'Kent', 'New Castle', 'Sussex', 'District of Columbia',
       'Alachua', 'Baker', 'Bay', 'Brevard', 'Broward', 'Citrus',
       'Collier', 'Columbia', 'Duval', 'Escambia', 'Flagler', 'Hamilton',
       'Highlands', 'Hillsborough', 'Holmes', 'Indian River', 'Lee',
       'Leon', 'Liberty', 'Manatee', 'Marion', 'Martin', 'Miami-Dade',
       'Nassau', 'Okaloosa', 'Osceola', 'Palm Beach', 'Pasco', 'Pinellas',
       'Putnam', 'Santa Rosa', 'Sarasota', 'Seminole', 'St. Lucie',
       'Volusia', 'Wakulla', 'Bibb', 'Charlton', 'Chatham', 'Chattooga',
       'Clarke', 'Clayton', 'Cobb', 'Coffee', 'Coweta', 'Dawson',
       'Dougherty', 'Floyd', 'Fulton', 'Glynn', 'Gwinnett', 'Hall',
       'Henry', 'Lowndes', 'Murray', 'Muscogee', 'Paulding', 'Pike',
       'Richmond', 'Rockdale', 'Walker', 'Hawaii', 'Honolulu', 'Kauai',
       'Maui', 'Ada', 'Bannock', 'Benewah', 'Blaine', 'Boise', 'Bonner',
       'Bonneville', 'Canyon', 'Custer', 'Franklin', 'Idaho', 'Jerome',
       'Kootenai', 'Latah', 'Lemhi', 'Nez Perce', 'Shoshone',
       'Twin Falls', 'Valley', 'Champaign', 'Cook', 'DuPage', 'Effingham',
       'Jersey', 'Jo Daviess', 'Kane', 'Macon', 'Macoupin', 'McHenry',
       'McLean', 'Peoria', 'Randolph', 'Rock Island', 'Saint Clair',
       'Sangamon', 'Will', 'Winnebago', 'Allen', 'Bartholomew', 'Boone',
       'Brown', 'Carroll', 'Delaware', 'Dubois', 'Elkhart', 'Greene',
       'Hendricks', 'Howard', 'Huntington', 'Johnson', 'Knox', 'LaPorte',
       'Monroe', 'Perry', 'Porter', 'Posey', 'Spencer', 'St. Joseph',
       'Sullivan', 'Tippecanoe', 'Vanderburgh', 'Vigo', 'Wabash',
       'Warrick', 'Whitley', 'Black Hawk', 'Bremer', 'Cerro Gordo',
       'Clinton', 'Harrison', 'Linn', 'Muscatine', 'Palo Alto',
       'Pottawattamie', 'Scott', 'Van Buren', 'Warren', 'Woodbury',
       'Chase', 'Ford', 'Leavenworth', 'Neosho', 'Sedgwick', 'Shawnee',
       'Sherman', 'Sumner', 'Trego', 'Wyandotte', 'Bell', 'Boyd',
       'Bullitt', 'Campbell', 'Carter', 'Christian', 'Daviess',
       'Edmonson', 'Fayette', 'Greenup', 'Hancock', 'Hardin', 'Henderson',
       'Jessamine', 'Livingston', 'McCracken', 'Oldham', 'Simpson',
       'Trigg', 'Ascension', 'Bossier', 'Caddo', 'Calcasieu',
       'East Baton Rouge', 'Iberville', 'Lafayette', 'Lafourche',
       'Orleans', 'Ouachita', 'Pointe Coupee', 'Rapides', 'St. Bernard',
       'St. James', 'St. John the Baptist', 'St. Martin', 'St. Tammany',
       'Tangipahoa', 'Terrebonne', 'West Baton Rouge', 'Androscoggin',
       'Aroostook', 'Cumberland', 'Kennebec', 'Oxford', 'Penobscot',
       'York', 'Anne Arundel', 'Baltimore', 'Baltimore (City)', 'Calvert',
       'Cecil', 'Charles', 'Dorchester', 'Frederick', 'Garrett',
       'Harford', "Prince George's", 'Barnstable', 'Berkshire', 'Bristol',
       'Dukes', 'Essex', 'Hampden', 'Hampshire', 'Norfolk', 'Plymouth',
       'Suffolk', 'Worcester', 'Allegan', 'Benzie', 'Berrien', 'Cass',
       'Chippewa', 'Genesee', 'Huron', 'Ingham', 'Kalamazoo', 'Keweenaw',
       'Lenawee', 'Macomb', 'Manistee', 'Mason', 'Missaukee', 'Muskegon',
       'Oakland', 'Ottawa', 'Schoolcraft', 'St. Clair', 'Tuscola',
       'Washtenaw', 'Wayne', 'Wexford', 'Anoka', 'Becker', 'Beltrami',
       'Carlton', 'Crow Wing', 'Dakota', 'Goodhue', 'Hennepin', 'Lyon',
       'Mille Lacs', 'Olmsted', 'Ramsey', 'Saint Louis', 'Stearns',
       'Winona', 'Wright', 'Bolivar', 'DeSoto', 'Forrest', 'Grenada',
       'Hinds', 'Lauderdale', 'Yalobusha', 'Andrew', 'Buchanan',
       'Callaway', 'Cedar', 'Jasper', 'Lincoln', 'Saint Charles',
       'Sainte Genevieve', 'St. Louis City', 'Stoddard', 'Taney',
       'Cascade', 'Fergus', 'Flathead', 'Gallatin', 'Lewis and Clark',
       'Missoula', 'Phillips', 'Powder River', 'Powell', 'Ravalli',
       'Richland', 'Roosevelt', 'Rosebud', 'Sanders', 'Sheridan',
       'Silver Bow', 'Yellowstone', 'Lancaster', 'Sarpy', 'Scotts Bluff',
       'Thomas', 'Carson City', 'Churchill', 'Elko', 'Nye', 'Washoe',
       'White Pine', 'Belknap', 'Cheshire', 'Coos', 'Grafton',
       'Merrimack', 'Rockingham', 'Atlantic', 'Bergen', 'Camden',
       'Gloucester', 'Hudson', 'Hunterdon', 'Mercer', 'Monmouth',
       'Morris', 'Ocean', 'Passaic', 'Bernalillo', 'Catron', 'Chaves',
       'Dona Ana', 'Eddy', 'Lea', 'Los Alamos', 'Luna', 'Rio Arriba',
       'Sandoval', 'Santa Fe', 'Socorro', 'Taos', 'Valencia', 'Albany',
       'Bronx', 'Chautauqua', 'Dutchess', 'Erie', 'Herkimer', 'New York',
       'Niagara', 'Oneida', 'Onondaga', 'Oswego', 'Queens', 'Rockland',
       'Saratoga', 'Steuben', 'Tompkins', 'Westchester', 'Alexander',
       'Avery', 'Buncombe', 'Caldwell', 'Carteret', 'Caswell', 'Catawba',
       'Davidson', 'Durham', 'Edgecombe', 'Forsyth', 'Graham',
       'Granville', 'Guilford', 'Haywood', 'Hyde', 'Johnston', 'Lenoir',
       'Mecklenburg', 'Mitchell', 'New Hanover', 'Person', 'Pitt',
       'Rowan', 'Swain', 'Wake', 'Yancey', 'Billings', 'Burke',
       'Burleigh', 'Dunn', 'McKenzie', 'Oliver', 'Stutsman', 'Ward',
       'Williams', 'Ashtabula', 'Athens', 'Belmont', 'Butler', 'Clermont',
       'Columbiana', 'Cuyahoga', 'Geauga', 'Licking', 'Lorain', 'Lucas',
       'Mahoning', 'Medina', 'Miami', 'Noble', 'Portage', 'Preble',
       'Scioto', 'Stark', 'Summit', 'Trumbull', 'Wood', 'Adair', 'Bryan',
       'Canadian', 'Cherokee', 'Choctaw', 'Cleveland', 'Comanche',
       'Creek', 'Dewey', 'Grady', 'Kay', 'Love', 'Mayes', 'McClain',
       'Muskogee', 'Oklahoma', 'Osage', 'Pittsburg', 'Sequoyah', 'Tulsa',
       'Benton', 'Clackamas', 'Crook', 'Deschutes', 'Grant', 'Harney',
       'Josephine', 'Klamath', 'Lane', 'Multnomah', 'Umatilla', 'Wallowa',
       'Wasco', 'Allegheny', 'Armstrong', 'Beaver', 'Berks', 'Blair',
       'Bradford', 'Bucks', 'Cambria', 'Centre', 'Chester', 'Clearfield',
       'Dauphin', 'Elk', 'Indiana', 'Lackawanna', 'Lebanon', 'Lehigh',
       'Luzerne', 'Lycoming', 'Northampton', 'Philadelphia', 'Somerset',
       'Tioga', 'Westmoreland', 'Adjuntas', 'Bayamon', 'Caguas', 'Catano',
       'Fajardo', 'Guayama', 'Guayanilla', 'Guaynabo', 'Juncos', 'Ponce',
       'Providence', 'Abbeville', 'Aiken', 'Anderson', 'Berkeley',
       'Charleston', 'Chesterfield', 'Colleton', 'Darlington',
       'Edgefield', 'Florence', 'Georgetown', 'Greenville', 'Horry',
       'Lexington', 'Oconee', 'Pickens', 'Spartanburg', 'Brookings',
       'Codington', 'Hughes', 'Meade', 'Minnehaha', 'Pennington',
       'Blount', 'Claiborne', 'Dyer', 'Loudon', 'Maury', 'McMinn',
       'Roane', 'Sevier', 'Williamson', 'Wilson', 'Bexar', 'Bowie',
       'Brazoria', 'Brewster', 'Cameron', 'Collin', 'Culberson', 'Dallas',
       'Denton', 'Ector', 'Ellis', 'Galveston', 'Gregg', 'Harris',
       'Hidalgo', 'Hood', 'Hunt', 'Kaufman', 'Kleberg', 'Lubbock',
       'Maverick', 'McLennan', 'Navarro', 'Nueces', 'Parker', 'Potter',
       'Randall', 'Rockwall', 'Smith', 'Tarrant', 'Travis', 'Victoria',
       'Webb', 'Box Elder', 'Cache', 'Carbon', 'Davis', 'Duchesne',
       'Salt Lake', 'Tooele', 'Uintah', 'Utah', 'Weber', 'Bennington',
       'Chittenden', 'Rutland', 'St Croix', 'St John', 'Albemarle',
       'Alexandria City', 'Arlington', 'Bristol City', 'Caroline',
       'Fairfax', 'Fauquier', 'Fredericksburg City', 'Giles',
       'Hampton City', 'Hanover', 'Henrico', 'Hopewell City', 'Loudoun',
       'Lynchburg City', 'Norfolk City', 'Prince Edward',
       'Prince William', 'Richmond City', 'Roanoke', 'Rockbridge',
       'Salem City', 'Stafford', 'Suffolk City', 'Virginia Beach City',
       'Winchester City', 'Wythe', 'Asotin', 'Chelan', 'Clallam',
       'Cowlitz', 'Grays Harbor', 'King', 'Kitsap', 'Kittitas',
       'Klickitat', 'Lewis', 'Okanogan', 'Pierce', 'Skagit', 'Snohomish',
       'Spokane', 'Stevens', 'Thurston', 'Walla Walla', 'Whatcom',
       'Whitman', 'Yakima', 'Brooke', 'Cabell', 'Gilmer', 'Greenbrier',
       'Kanawha', 'Marshall', 'Monongalia', 'Ohio', 'Tucker', 'Ashland',
       'Dane', 'Dodge', 'Door', 'Eau Claire', 'Fond du Lac', 'Forest',
       'Kenosha', 'Kewaunee', 'La Crosse', 'Manitowoc', 'Marathon',
       'Milwaukee', 'Outagamie', 'Ozaukee', 'Racine', 'Rock', 'Sauk',
       'Sheboygan', 'Taylor', 'Vilas', 'Walworth', 'Waukesha', 'Big Horn',
       'Converse', 'Laramie', 'Natrona', 'Platte', 'Sublette',
       'Sweetwater', 'Teton', 'Uinta', 'Weston', 'Bethel ', 'Craighead',
       'Teller', 'Le Flore', 'Nowata', 'Susquehanna', 'Iron', 'St Thomas'],
      dtype=object)

In [12]:
aqi_sb = aqi[aqi['county_name'] == 'Santa Barbara']
aqi_sb = aqi.drop(columns=['state_name', 'county_name', 'state_code','county_code'])
aqi_sb

,date,aqi,category,defining_parameter,defining_site,number_of_sites_reporting
0,2017-01-01,28,Good,PM2.5,01-003-0010,1
1,2017-01-04,29,Good,PM2.5,01-003-0010,1
2,2017-01-10,25,Good,PM2.5,01-003-0010,1
3,2017-01-13,40,Good,PM2.5,01-003-0010,1
4,2017-01-16,22,Good,PM2.5,01-003-0010,1
...,...,...,...,...,...,...
327536,2018-12-27,36,Good,Ozone,56-045-0003,1
327537,2018-12-28,35,Good,Ozone,56-045-0003,1
327538,2018-12-29,35,Good,Ozone,56-045-0003,1
327539,2018-12-30,31,Good,Ozone,56-045-0003,1
327540,2018-12-31,35,Good,Ozone,56-045-0003,1

In [13]:
grader.check("q6a")

q6a results: All test cases passed!

 
c. What is the data type of the `date` column? Write your answer in the markdown cell below.

*Your answer here.*

In [14]:
aqi["date"].info()

<class 'pandas.core.series.Series'>
Index: 654342 entries, 0 to 327540
Series name: date
Non-Null Count   Dtype
--------------   -----
654342 non-null  object
dtypes: object(1)
memory usage: 10.0+ MB

The dtype of the date column is an object.

<!-- BEGIN QUESTION -->

## 7
In the following cell:
1. Update the `date` column of `aqi_sb` to have the `datetime64` data type.
2. Update the index of `aqi_sb` to be the `date` column.

In [25]:
aqi_sb['date'] = pd.to_datetime(aqi_sb['date'])

In [27]:
aqi_sb = aqi_sb.set_index('date')

KeyError: "None of ['date'] are in the columns"

In [28]:
aqi_sb

,aqi,category,defining_parameter,defining_site,number_of_sites_reporting
date,,,,,
2017-01-01,28,Good,PM2.5,01-003-0010,1
2017-01-04,29,Good,PM2.5,01-003-0010,1
2017-01-10,25,Good,PM2.5,01-003-0010,1
2017-01-13,40,Good,PM2.5,01-003-0010,1
2017-01-16,22,Good,PM2.5,01-003-0010,1
...,...,...,...,...,...
2018-12-27,36,Good,Ozone,56-045-0003,1
2018-12-28,35,Good,Ozone,56-045-0003,1
2018-12-29,35,Good,Ozone,56-045-0003,1
2018-12-30,31,Good,Ozone,56-045-0003,1
2018-12-31,35,Good,Ozone,56-045-0003,1

<!-- END QUESTION -->

## 8
In the next cell we will calculate an average over a [rolling window](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.rolling.html) using the `rolling()` method for `pandas.Series`:

- `rolling()` is a lazy method, so we need to specify what we want to calculate over each window before it does something. 
- in this example we use the aggregator function `mean()` to calculate the average over each window
- the parameter '5D' indicates we want the window for our rolling average to be 5 days. 
- we get a `pandas.Series` as output

Store your answer in the `rolling_average` variable. Your result should be a `pandas.Series` indexed by `date`, with the 5-day averages as its values.

In [16]:
# Calculate AQI rolling average over 5 days
rolling_average = ...
rolling_average

Ellipsis

In [17]:
grader.check("q8")

q8 results:
    q8 - 1 result:
        ❌ Test case failed
        Trying:
            pd.testing.assert_frame_equal(pd.read_csv('data/t3_q8_df.csv', index_col='date', parse_dates=True), pd.DataFrame(rolling_average))
        Expecting nothing
        **********************************************************************
        Line 1, in q8 0
        Failed example:
            pd.testing.assert_frame_equal(pd.read_csv('data/t3_q8_df.csv', index_col='date', parse_dates=True), pd.DataFrame(rolling_average))
        Exception raised:
            Traceback (most recent call last):
              File "/opt/miniforge3/envs/eds220-v2/lib/python3.11/doctest.py", line 1351, in __run
                exec(compile(example.source, filename, "single",
              File "<doctest q8 0[0]>", line 1, in <module>
                pd.testing.assert_frame_equal(pd.read_csv('data/t3_q8_df.csv', index_col='date', parse_dates=True), pd.DataFrame(rolling_average))
                                                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/opt/miniforge3/envs/eds220-v2/lib/python3.11/site-packages/pandas/core/frame.py", line 890, in __init__
                raise ValueError("DataFrame constructor not properly called!")
            ValueError: DataFrame constructor not properly called!

## 9 

Without creating any new variables, add the mean of the AQI over a 5-day rolling window as a new column named `five_day_average` to the `aqi_sb` data frame.

In [18]:
aqi_sb

,date,aqi,category,defining_parameter,defining_site,number_of_sites_reporting
0,2017-01-01,28,Good,PM2.5,01-003-0010,1
1,2017-01-04,29,Good,PM2.5,01-003-0010,1
2,2017-01-10,25,Good,PM2.5,01-003-0010,1
3,2017-01-13,40,Good,PM2.5,01-003-0010,1
4,2017-01-16,22,Good,PM2.5,01-003-0010,1
...,...,...,...,...,...,...
327536,2018-12-27,36,Good,Ozone,56-045-0003,1
327537,2018-12-28,35,Good,Ozone,56-045-0003,1
327538,2018-12-29,35,Good,Ozone,56-045-0003,1
327539,2018-12-30,31,Good,Ozone,56-045-0003,1
327540,2018-12-31,35,Good,Ozone,56-045-0003,1

In [19]:
grader.check("q9")

q9 results:
    q9 - 1 result:
        ❌ Test case failed
        Trying:
            def test_q9(aqi_sb):
                try:
                    expected_data = pd.read_csv('data/t3_q9_df.csv', index_col='date', parse_dates=True)
                    pd.testing.assert_frame_equal(expected_data, aqi_sb)
                except AssertionError:
                    raise AssertionError('Incorrect answer.')
        Expecting nothing
        ok
        Trying:
            test_q9(aqi_sb)
        Expecting nothing
        **********************************************************************
        Line 7, in q9 0
        Failed example:
            test_q9(aqi_sb)
        Exception raised:
            Traceback (most recent call last):
              File "<doctest q9 0[0]>", line 4, in test_q9
                pd.testing.assert_frame_equal(expected_data, aqi_sb)
              File "/opt/miniforge3/envs/eds220-v2/lib/python3.11/site-packages/pandas/_testing/asserters.py", line 1242, in assert_frame_equal
                raise_assert_detail(
              File "/opt/miniforge3/envs/eds220-v2/lib/python3.11/site-packages/pandas/_testing/asserters.py", line 620, in raise_assert_detail
                raise AssertionError(msg)
            AssertionError: DataFrame are different

            DataFrame shape mismatch
            [left]:  (730, 6)
            [right]: (654342, 6)

            During handling of the above exception, another exception occurred:

            Traceback (most recent call last):
              File "/opt/miniforge3/envs/eds220-v2/lib/python3.11/doctest.py", line 1351, in __run
                exec(compile(example.source, filename, "single",
              File "<doctest q9 0[1]>", line 1, in <module>
                test_q9(aqi_sb)
              File "<doctest q9 0[0]>", line 6, in test_q9
                raise AssertionError('Incorrect answer.')
            AssertionError: Incorrect answer.

<!-- BEGIN QUESTION -->

## 10
Make a line plot showing both the daily AQI and the 5-day average (5-day average on top of the AQI). Make necessary updates for the plot to be accurate, informative, and polished, even if simple. You're welcome to use plotting methods and packages beyond what we have covered in class! 

Can you see the AQI going up during the Thomas Fire in December 2017?

---

To double-check your work, the cell below will rerun all of the autograder tests.

In [20]:
grader.check_all()

q3_a results: All test cases passed!

q4 results: All test cases passed!

q6a results: All test cases passed!

q8 results:
    q8 - 1 result:
        ❌ Test case failed
        Trying:
            pd.testing.assert_frame_equal(pd.read_csv('data/t3_q8_df.csv', index_col='date', parse_dates=True), pd.DataFrame(rolling_average))
        Expecting nothing
        **********************************************************************
        Line 1, in q8 0
        Failed example:
            pd.testing.assert_frame_equal(pd.read_csv('data/t3_q8_df.csv', index_col='date', parse_dates=True), pd.DataFrame(rolling_average))
        Exception raised:
            Traceback (most recent call last):
              File "/opt/miniforge3/envs/eds220-v2/lib/python3.11/doctest.py", line 1351, in __run
                exec(compile(example.source, filename, "single",
              File "<doctest q8 0[0]>", line 1, in <module>
                pd.testing.assert_frame_equal(pd.read_csv('data/t3_q8_df.csv', index_col='date', parse_dates=True), pd.DataFrame(rolling_average))
                                                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/opt/miniforge3/envs/eds220-v2/lib/python3.11/site-packages/pandas/core/frame.py", line 890, in __init__
                raise ValueError("DataFrame constructor not properly called!")
            ValueError: DataFrame constructor not properly called!

q9 results:
    q9 - 1 result:
        ❌ Test case failed
        Trying:
            def test_q9(aqi_sb):
                try:
                    expected_data = pd.read_csv('data/t3_q9_df.csv', index_col='date', parse_dates=True)
                    pd.testing.assert_frame_equal(expected_data, aqi_sb)
                except AssertionError:
                    raise AssertionError('Incorrect answer.')
        Expecting nothing
        ok
        Trying:
            test_q9(aqi_sb)
        Expecting nothing
        **********************************************************************
        Line 7, in q9 0
        Failed example:
            test_q9(aqi_sb)
        Exception raised:
            Traceback (most recent call last):
              File "<doctest q9 0[0]>", line 4, in test_q9
                pd.testing.assert_frame_equal(expected_data, aqi_sb)
              File "/opt/miniforge3/envs/eds220-v2/lib/python3.11/site-packages/pandas/_testing/asserters.py", line 1242, in assert_frame_equal
                raise_assert_detail(
              File "/opt/miniforge3/envs/eds220-v2/lib/python3.11/site-packages/pandas/_testing/asserters.py", line 620, in raise_assert_detail
                raise AssertionError(msg)
            AssertionError: DataFrame are different

            DataFrame shape mismatch
            [left]:  (730, 6)
            [right]: (654342, 6)

            During handling of the above exception, another exception occurred:

            Traceback (most recent call last):
              File "/opt/miniforge3/envs/eds220-v2/lib/python3.11/doctest.py", line 1351, in __run
                exec(compile(example.source, filename, "single",
              File "<doctest q9 0[1]>", line 1, in <module>
                test_q9(aqi_sb)
              File "<doctest q9 0[0]>", line 6, in test_q9
                raise AssertionError('Incorrect answer.')
            AssertionError: Incorrect answer.

<!-- END QUESTION -->

## 11


Collect all the relevant code into the first blank cell of the notebook titled "COMPLETE WORKFLOW". This single cell will have the end-to-end workflow: from importing libraries and loading the data, to producing the graph. The *only* output of this cell should be the graph you produced in the previous exercise. Further guidance on what to include in this final workflow is in the [assignment rubric](https://docs.google.com/document/d/1x0BoU6IH4cnOR1-n7i9CYQ9wUC37yDpYlQ4j6rCfcsU/edit?tab=t.0).